services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - node.name=es-node
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.enrollment.enabled=true
#      - ELASTIC_PASSWORD=changeme123
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -u elastic:changeme123 -f http://localhost:9200 || exit 1"]
      interval: 10s
      retries: 5

  app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
#      - ELASTIC_USER=elastic
#      - ELASTIC_PASSWORD=changeme123
    depends_on:
      elasticsearch:
        condition: service_healthy
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]

networks:
  app-network:

volumes:
  es_data:
